### PR TITLE
Add a test case for undeploy unselected deployment

### PR DESCRIPTION
**Pull request by ypu**
This is a new test case for undeploy unselected deployment by command "os admin undeploy".

The scenario 2 need the code update from https://github.com/aweiteka/UATFramework/pull/65

### CODE REVIEW

**Comment by miabbott** [comment]
While I like the spirit of this test, I don't think it is applicable for RHEL Atomic Host at the moment.  

Customers will not be using the `ostree admin undeploy` command right now, so it is not critical to have this test.

I would suggest creating a new directory `features/ostree` and moving this test into there.

**Comment by ypu** [comment]
@miabbott OK thanks for your advise. Will update it.

**Comment by ypu** [comment]
Hi @miabbott Already make it separated to ostree directory. Can you help to review it again?

**Comment by miabbott** [comment]
:+1:

**Pull request merged**
