### PR TITLE
refactor feature directory

### PR DESCRIPTION
**Pull request by chuanchang**
RHEL Atomic Host should be a full stack docker, including docker, k8s, etcd, atomic host(atomic, ostree and rpm-ostree cmdline, etc), etc,  so to move atomic/ directory into rhelah/ and mkdir {docker, k8s, etcd} subdir under the rhelah/, meanwhile, move features from rhelah/atomic/ to relevant subdir, I have no good idea for tree_gpg_signed.feature, only leave it in rhelah/atomic, if you have good advice, please let me know, thanks!

The final directory tree looks like this:

[root@myrhel7 features]# tree
.
├── cdk
│   ├── rht-registration-from-rubygems.feature
│   └── rht-registration-from-source.feature
├── examples
│   ├── openshift.feature
│   └── satellite.feature
├── rhelah
│   ├── atomic
│   │   ├── atomic_images.feature
│   │   ├── atomic_info.feature
│   │   ├── atomic_mount_unmount.feature
│   │   ├── multiple_rollback.feature
│   │   ├── multiple_rollback_reboot.feature
│   │   ├── no_refs_to_cdn_stage.feature
│   │   ├── rollback_multi_interrupt.feature
│   │   ├── rollback_single_interrupt.feature
│   │   ├── sanity_new_qcow.feature
│   │   ├── sanity_new_tree.feature
│   │   ├── tree_gpg_signed.feature
│   │   ├── unique_machine-id.feature
│   │   ├── upgrade_multi_interrupt.feature
│   │   └── upgrade_single_interrupt.feature
│   ├── docker
│   │   └── docker_pull.feature
│   ├── etcd
│   ├── k8s
│   │   └── cluster.feature
│   └── smoketest.feature
└── subman
    ├── subman_bad_password.feature
    ├── subman_bad_pool_list.feature
    ├── subman_bad_pool_scalar.feature
    ├── subman_bad_repoid.feature
    ├── subman_bad_subscription_keys.feature
    ├── subman_bad_username.feature
    ├── subman_mixed_pool_list.feature
    ├── subman_ok.feature
    └── subman_reenable_redisable_repoids.feature

Signed-off-by: Alex Jia ajia@redhat.com

### CODE REVIEW

**Comment by ypu** [comment]
Like the idea to make the structure more clear. This also help to test each component. So 

Acked-by: Yiqiao Pu ypu@redhat.com

**Comment by miabbott** [comment]
Thanks for the re-org @chuanchang!

I think your new directory structure makes sense.  I think we could also apply this to the `steps` files, too (but in another PR).

One of the side effects is that our internal Jenkins jobs will have to be updated to point to these new locations, but I think that is relatively minor problem.

@jlebon @ljozsa @gouyang I'd encourage you all to comment, if you could.

**Comment by jlebon** [comment]
@miabbott Thanks for notifying me (finally added myself to the watch list). Yes, it makes sense to have atomic, docker, k8s, etc... under rhelah instead.

**Comment by gouyang** [comment]
I'm so so on this, but I will not object to it.

This is a public repository and there are incoming users soon or later(we hope so, right?), rhelah just make sense to us and these who would like to use it, but not for these who don't use RHELAH.

My opinion is that we should make the testings more generally. Only RHELAH specified testings goes into feature/rhelah. In case of someone who would like to add something for other host environment like coreos, they just only need to add coreos specified to feature/coreos.

**Comment by chuanchang** [comment]
@miabbott,  I forgot to mention it in my comments, yes, our internal Jenkins jobs need to be modified to follow this change.

**Comment by miabbott** [comment]
@gouyang I agree that we could make tests more generic and we should try to do so in other PRs.

I think laying the groundwork for that work by adopting this new directory structure would be helpful.

I think this can be merged safely, however there is some critical testing upcoming and I'd rather wait a few more days until it has been completed before merging.

**Comment by gouyang** [comment]
it's helpful to us for sure, I'm not objecting to merge this.

**Comment by miabbott** [comment]
Thanks @chuanchang for the PR!

**Pull request merged**
