### PR TITLE
rhelah: update status methods to use JSON output

### PR DESCRIPTION
**Pull request by miabbott**
Newer versions of `rpm-ostree` and `atomic host status` now support
JSON output.

This change updates the methods which use the output from `atomic host
status` to use the JSON output, rather than using a regexp on the string output from the command.

### CODE REVIEW

**Comment by miabbott** [comment]
@chuanchang @johnbieren  Only did some light testing with this, so there may be errors

**Comment by chuanchang** [comment]
@miabbott, sorry for delaying review, could you rebase this one? thanks.

**Comment by miabbott** [comment]
@chuanchang I don't see any conflicts that need rebasing...

**Comment by johnbieren** [comment]
@miabbott Sorry, took me a while to setup my automated environment with a current enough release of atomic to use --json.  In get_atomic_status, you have return json.loads(status_result).  This fails for me because status_result is of type list and you can't json.loads a list.  I believe you need something like return json.loads(status_result[0]["stdout"]), but I'm not positive.

**Comment by miabbott** [comment]
@johnbieren Yeah you are right.  I totally mangled those methods by ignoring the fact that there might be more than one host the tests are running against.

I'll have to re-work this change.

**Comment by miabbott** [comment]
The back to back RHELAH releases have me swamped and I haven't had time to look at this again.

If someone wants to pick up this PR and re-work it correctly, that would be OK with me.

**Pull request closed without merging**
