### PR TITLE
Tests for CDK

### PR DESCRIPTION
**Pull request by langdon**
- created new feature directory for cdk features
- added vagrant_plugin as a background variable
- added target_host as a background variable
- provided some inheritance via execute_step to allow background variable defaults
- removed "vagrant" feature
- added github steps file
- scoped vagrant steps file

### CODE REVIEW

**Comment by aweiteka** [comment]
Code looks good. I'll merge after you rebase from master to remove a bunch of old commits. I recommend creating a branch, resync upstream master, the rebase master onto the dev branch, push the branch to your fork. You'll probably need to change the PR to use the new branch. Something like this:
1. `git checkout -b vagrant`
2. Sync upstream master per https://help.github.com/articles/syncing-a-fork/
3. `git checkout vagrant`
4. `git rebase master`
5. `git push origin vagrant`
6. Go to the web to update this PR if necessary

**Comment by miabbott** [comment]
In steps/vagrant.py, there are instances where the **host** argument to **step_impl()** defaults to "cihosts".  Example:

https://github.com/whitel/UATFramework/blob/9cafecde2784f9a8ab272b4c7acafa8e48e77638/steps/vagrant.py#L33

I know that our particular CI environment is the primary consumer of this framework, but I think we should make it more flexible and have **host** default to None or give it no default value.

**Comment by aweiteka** [comment]
@miabbott yes, this was a bit of a hack that needed to be addressed. I'm okay merging as is but it should be looked at.

**Comment by langdon** [comment]
I had actually started removing those (cihosts) but wasn't sure if it was "by design." I can remove the rest and use just the background variable. Did you notice I stuck it in context.target_host? Is that the best choice?

**Pull request closed without merging**
